# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kvstore_pb2 as kvstore__pb2


class KVStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/kvstore.KVStore/Get',
                request_serializer=kvstore__pb2.GetRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GetResponse.FromString,
                )
        self.Put = channel.unary_unary(
                '/kvstore.KVStore/Put',
                request_serializer=kvstore__pb2.PutRequest.SerializeToString,
                response_deserializer=kvstore__pb2.PutResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/kvstore.KVStore/Delete',
                request_serializer=kvstore__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kvstore__pb2.DeleteResponse.FromString,
                )
        self.BatchGet = channel.unary_unary(
                '/kvstore.KVStore/BatchGet',
                request_serializer=kvstore__pb2.BatchGetRequest.SerializeToString,
                response_deserializer=kvstore__pb2.BatchGetResponse.FromString,
                )
        self.BatchPut = channel.unary_unary(
                '/kvstore.KVStore/BatchPut',
                request_serializer=kvstore__pb2.BatchPutRequest.SerializeToString,
                response_deserializer=kvstore__pb2.BatchPutResponse.FromString,
                )
        self.SetReplicationMode = channel.unary_unary(
                '/kvstore.KVStore/SetReplicationMode',
                request_serializer=kvstore__pb2.SetReplicationModeRequest.SerializeToString,
                response_deserializer=kvstore__pb2.SetReplicationModeResponse.FromString,
                )
        self.Die = channel.unary_unary(
                '/kvstore.KVStore/Die',
                request_serializer=kvstore__pb2.DieRequest.SerializeToString,
                response_deserializer=kvstore__pb2.DieResponse.FromString,
                )
        self.Ping = channel.unary_unary(
                '/kvstore.KVStore/Ping',
                request_serializer=kvstore__pb2.PingRequest.SerializeToString,
                response_deserializer=kvstore__pb2.PingResponse.FromString,
                )


class KVStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReplicationMode(self, request, context):
        """To dynamically switch replication modes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Die(self, request, context):
        """New Die RPC method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """New Ping RPC method
        Add this line
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kvstore__pb2.GetRequest.FromString,
                    response_serializer=kvstore__pb2.GetResponse.SerializeToString,
            ),
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kvstore__pb2.PutRequest.FromString,
                    response_serializer=kvstore__pb2.PutResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kvstore__pb2.DeleteRequest.FromString,
                    response_serializer=kvstore__pb2.DeleteResponse.SerializeToString,
            ),
            'BatchGet': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGet,
                    request_deserializer=kvstore__pb2.BatchGetRequest.FromString,
                    response_serializer=kvstore__pb2.BatchGetResponse.SerializeToString,
            ),
            'BatchPut': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchPut,
                    request_deserializer=kvstore__pb2.BatchPutRequest.FromString,
                    response_serializer=kvstore__pb2.BatchPutResponse.SerializeToString,
            ),
            'SetReplicationMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReplicationMode,
                    request_deserializer=kvstore__pb2.SetReplicationModeRequest.FromString,
                    response_serializer=kvstore__pb2.SetReplicationModeResponse.SerializeToString,
            ),
            'Die': grpc.unary_unary_rpc_method_handler(
                    servicer.Die,
                    request_deserializer=kvstore__pb2.DieRequest.FromString,
                    response_serializer=kvstore__pb2.DieResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=kvstore__pb2.PingRequest.FromString,
                    response_serializer=kvstore__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.KVStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KVStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/Get',
            kvstore__pb2.GetRequest.SerializeToString,
            kvstore__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/Put',
            kvstore__pb2.PutRequest.SerializeToString,
            kvstore__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/Delete',
            kvstore__pb2.DeleteRequest.SerializeToString,
            kvstore__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/BatchGet',
            kvstore__pb2.BatchGetRequest.SerializeToString,
            kvstore__pb2.BatchGetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/BatchPut',
            kvstore__pb2.BatchPutRequest.SerializeToString,
            kvstore__pb2.BatchPutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetReplicationMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/SetReplicationMode',
            kvstore__pb2.SetReplicationModeRequest.SerializeToString,
            kvstore__pb2.SetReplicationModeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Die(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/Die',
            kvstore__pb2.DieRequest.SerializeToString,
            kvstore__pb2.DieResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.KVStore/Ping',
            kvstore__pb2.PingRequest.SerializeToString,
            kvstore__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MasterNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHead = channel.unary_unary(
                '/kvstore.MasterNode/GetHead',
                request_serializer=kvstore__pb2.GetHeadRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GetHeadResponse.FromString,
                )
        self.GetTail = channel.unary_unary(
                '/kvstore.MasterNode/GetTail',
                request_serializer=kvstore__pb2.GetTailRequest.SerializeToString,
                response_deserializer=kvstore__pb2.GetTailResponse.FromString,
                )
        self.SendHeartbeat = channel.unary_unary(
                '/kvstore.MasterNode/SendHeartbeat',
                request_serializer=kvstore__pb2.SendHeartbeatRequest.SerializeToString,
                response_deserializer=kvstore__pb2.SendHeartbeatResponse.FromString,
                )


class MasterNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHead': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHead,
                    request_deserializer=kvstore__pb2.GetHeadRequest.FromString,
                    response_serializer=kvstore__pb2.GetHeadResponse.SerializeToString,
            ),
            'GetTail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTail,
                    request_deserializer=kvstore__pb2.GetTailRequest.FromString,
                    response_serializer=kvstore__pb2.GetTailResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=kvstore__pb2.SendHeartbeatRequest.FromString,
                    response_serializer=kvstore__pb2.SendHeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kvstore.MasterNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MasterNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.MasterNode/GetHead',
            kvstore__pb2.GetHeadRequest.SerializeToString,
            kvstore__pb2.GetHeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.MasterNode/GetTail',
            kvstore__pb2.GetTailRequest.SerializeToString,
            kvstore__pb2.GetTailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kvstore.MasterNode/SendHeartbeat',
            kvstore__pb2.SendHeartbeatRequest.SerializeToString,
            kvstore__pb2.SendHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
